
import Groq from "groq-sdk";
import { TripParams, Itinerary } from "../types";

const groq = new Groq({
    apiKey: process.env.GROQ_API_KEY || '',
    dangerouslyAllowBrowser: true
});

const ITINERARY_JSON_SCHEMA = JSON.stringify({
    type: "object",
    properties: {
        destination: { type: "string" },
        totalBudget: { type: "number" },
        duration: { type: "number" },
        currency: { type: "string" },
        days: {
            type: "array",
            items: {
                type: "object",
                properties: {
                    day: { type: "integer" },
                    accommodationCost: { type: "number" },
                    travelCost: { type: "number", description: "Daily local transportation cost (taxi, metro, auto, etc.)" },
                    activities: {
                        type: "array",
                        items: {
                            type: "object",
                            properties: {
                                id: { type: "string" },
                                name: { type: "string" },
                                description: { type: "string" },
                                timeSlot: { type: "string" },
                                cost: { type: "number" },
                                location: { type: "string" },
                                activityType: { type: "string" },
                                estimatedDuration: { type: "string" },
                                bestVisitingTime: { type: "string" },
                                localTips: { type: "array", items: { type: "string" } },
                                aiInsights: { type: "string" }
                            },
                            required: ["id", "name", "description", "timeSlot", "cost", "location", "activityType"]
                        }
                    }
                },
                required: ["day", "accommodationCost", "travelCost", "activities"]
            }
        }
    },
    required: ["destination", "totalBudget", "duration", "currency", "days"]
});

export const travelAgentService = {
    async draftPlan(params: TripParams): Promise<{ data: Itinerary, reasoning: string }> {
        // Calculate recommended activities per day based on budget
        const budgetPerDay = params.budget / params.days;
        let activitiesPerDay = 2; // Default minimum

        if (budgetPerDay > 15000) {
            activitiesPerDay = 5; // Luxury budget
        } else if (budgetPerDay > 8000) {
            activitiesPerDay = 4; // High budget
        } else if (budgetPerDay > 4000) {
            activitiesPerDay = 3; // Medium budget
        }

        const systemPrompt = `Act as an expert travel planner. Create an initial draft itinerary for a ${params.days}-day trip to ${params.destination} with a total budget of ${params.budget} INR.
    The user prefers: ${params.preferences.join(", ")}.
    
    IMPORTANT: Based on the budget of ₹${params.budget} (₹${budgetPerDay.toFixed(0)} per day), include approximately ${activitiesPerDay} activities per day.
    - Higher budgets should have more diverse and premium activities
    - Lower budgets should focus on essential and budget-friendly experiences
    - Include realistic daily travel costs (travelCost) for local transportation like metro, taxi, auto-rickshaw, etc.
    - Travel costs should be proportional to the number of activities and distances covered
    
    You MUST output valid JSON only, matching this schema:
    ${ITINERARY_JSON_SCHEMA}
    
    Do not include any markdown formatting or explanation outside the JSON.`;

        try {
            const completion = await groq.chat.completions.create({
                messages: [
                    { role: "system", content: systemPrompt },
                    { role: "user", content: "Generate the itinerary." }
                ],
                model: "llama-3.3-70b-versatile",
                temperature: 0.5,
                response_format: { type: "json_object" }
            });

            const content = completion.choices[0]?.message?.content || "{}";
            const itinerary = JSON.parse(content) as Itinerary;

            return {
                data: itinerary,
                reasoning: "Generated by Llama 3 via Groq based on your budget and preferences."
            };

        } catch (error) {
            console.error("Error creating draft plan with Groq:", error);
            throw error;
        }
    },

    async optimizePlan(params: TripParams, currentItinerary: Itinerary): Promise<{ data: Itinerary, adjustments: string[], status: 'perfect' | 'adjusted' }> {
        const currentTotal = currentItinerary.days.reduce((acc, d) => acc + d.activities.reduce((sum, a) => sum + a.cost, 0) + d.accommodationCost, 0);

        if (currentTotal <= params.budget) {
            return {
                data: currentItinerary,
                adjustments: ["Budget validation passed."],
                status: 'perfect'
            };
        }

        const prompt = `The trip to ${params.destination} costs ${currentTotal} but budget is ${params.budget}.
    Suggest specific reductions to meet the budget.
    Output JSON: { "adjustments": ["string"], "newTotal": number, "status": "adjusted" | "perfect" }`;

        try {
            const completion = await groq.chat.completions.create({
                messages: [
                    { role: "system", content: "You are a budget optimizer. Output valid JSON only." },
                    { role: "user", content: `Current Itinerary: ${JSON.stringify(currentItinerary)}\n\n${prompt}` }
                ],
                model: "llama-3.3-70b-versatile",
                response_format: { type: "json_object" }
            });

            const content = completion.choices[0]?.message?.content || "{}";
            const result = JSON.parse(content);

            return {
                data: currentItinerary,
                adjustments: result.adjustments || ["Optimized budget"],
                status: result.status || 'adjusted'
            };

        } catch (error) {
            console.error("Error optimizing plan with Groq:", error);
            throw error;
        }
    }
};
